### ISSUE TITLE
Data manipulation?

### ISSUE THREAD

**Issue by sle118** [akbooer/DataYours#1]
Hello and thanks for this super plugin!

I am using a home energy monitor from aeon labs and one of the parameters I am interested in is voltage. The problem with this is that the value is reported as kWh in the vets config. This means we see a value change event for each report going from 117.88 to 2765 then back to 117.76 then 2766... You get the point.

I was thinking about intercepting the value and based on a simple regex (or limit), redirect the value to a new whisper dB variable. Is this any possible, and if so, how?

**Comment by akbooer** [comment]
Yes, I've heard this is a problem with that device.

Yes, Graphite / DataYours is exactly designed to be able to insert other processing into the data acquisition chain.  Let's continue the discussion here: http://forum.micasaverde.com/index.php/topic,37119.0.html, which is a very relevant and recent thread.

**Comment by akbooer** [comment]
Now fixed with the release of User Defined Processing in DataWatcher.
